import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { appendGeneratedRule, loadGeneratedRules, promoteToRule } from "./promote.js";

function tmpFile(): string {
  const dir = mkdtempSync(join(tmpdir(), "sentinel-promote-"));
  return join(dir, "policy.generated.yaml");
}

describe("promoteToRule", () => {
  it("becomes an allow rule", () => {
    const rule = promoteToRule({
      rule_name: "x",
      match: { tool: "Bash", command_matches: "^curl\\b" },
    });
    expect(rule.action).toBe("allow");
    expect(rule.name).toBe("x");
    expect(rule.when.command_matches).toBe("^curl\\b");
  });

  it("carries repo_in", () => {
    const rule = promoteToRule({
      rule_name: "x",
      match: { tool: "Edit", path_matches: "\\.ts$", repo_in: ["wiki"] },
    });
    expect(rule.when.repo_in).toEqual(["wiki"]);
    expect(rule.when.path_matches).toBe("\\.ts$");
  });
});

describe("appendGeneratedRule / loadGeneratedRules", () => {
  it("creates file and round-trips a rule", async () => {
    const path = tmpFile();
    const rule = promoteToRule({
      rule_name: "Bash: curl",
      match: { tool: "Bash", command_matches: "^curl\\b" },
    });
    await appendGeneratedRule(path, rule);
    const loaded = await loadGeneratedRules(path);
    expect(loaded).toHaveLength(1);
    expect(loaded[0]?.name).toBe("Bash: curl");
    expect(loaded[0]?.action).toBe("allow");
    expect(loaded[0]?.when.command_matches).toBe("^curl\\b");
  });

  it("replaces rule with same name (no duplicates)", async () => {
    const path = tmpFile();
    const a = promoteToRule({
      rule_name: "X",
      match: { tool: "Bash", command_matches: "^foo\\b" },
    });
    const b = promoteToRule({
      rule_name: "X", // same name
      match: { tool: "Bash", command_matches: "^bar\\b" }, // different regex
    });
    await appendGeneratedRule(path, a);
    await appendGeneratedRule(path, b);
    const loaded = await loadGeneratedRules(path);
    expect(loaded).toHaveLength(1);
    expect(loaded[0]?.when.command_matches).toBe("^bar\\b");
  });

  it("appends distinct names", async () => {
    const path = tmpFile();
    await appendGeneratedRule(
      path,
      promoteToRule({ rule_name: "A", match: { tool: "Bash", command_matches: "^a\\b" } }),
    );
    await appendGeneratedRule(
      path,
      promoteToRule({ rule_name: "B", match: { tool: "Bash", command_matches: "^b\\b" } }),
    );
    const loaded = await loadGeneratedRules(path);
    expect(loaded.map((r) => r.name).sort()).toEqual(["A", "B"]);
  });

  it("loadGeneratedRules returns empty when file missing", async () => {
    const path = tmpFile();
    const loaded = await loadGeneratedRules(path);
    expect(loaded).toEqual([]);
  });

  it("includes header comment", async () => {
    const path = tmpFile();
    await appendGeneratedRule(
      path,
      promoteToRule({ rule_name: "x", match: { tool: "Bash", command_matches: "^x\\b" } }),
    );
    const raw = readFileSync(path, "utf-8");
    expect(raw).toMatch(/Auto-generated by Sentinel/u);
  });
});
