import { readFile, rename, writeFile } from "node:fs/promises";
import { type PolicyRule, PolicyRuleSchema, type PromoteRule } from "@sentinel/shared";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";

/**
 * ルール昇格 (Allow & promote to rule) で daemon が書き出すファイル。
 *
 * 設計:
 *  - ユーザー手書きの policy.yaml は触らない (コメント・順序を守るため)
 *  - 自動生成ルールは policy.generated.yaml に蓄積される
 *  - loader は両方をマージする (main の rules の後に generated の rules を追加)
 *  - generated 側は rules のみ (defaults は持たない)
 *
 * 書き込みは atomic (tmp に書いて rename)。
 */

export interface GeneratedRulesFile {
  rules: PolicyRule[];
}

/** generated 用の簡易スキーマ。defaults は持たない。 */
function parseGenerated(raw: string): GeneratedRulesFile {
  const parsed = parseYaml(raw);
  if (!parsed || typeof parsed !== "object") return { rules: [] };
  const obj = parsed as { rules?: unknown };
  if (!obj.rules || !Array.isArray(obj.rules)) return { rules: [] };
  const rules = obj.rules.map((r) => PolicyRuleSchema.parse(r));
  return { rules };
}

export async function loadGeneratedRules(path: string): Promise<PolicyRule[]> {
  try {
    const raw = await readFile(path, "utf-8");
    return parseGenerated(raw).rules;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw err;
  }
}

/**
 * PromoteRule (PWA から届く形式) を PolicyRule に変換する。
 * promote は常に action: allow として保存する (deny への昇格は Phase 7 では対応しない)。
 */
export function promoteToRule(p: PromoteRule, decidedBy?: string): PolicyRule {
  const when: PolicyRule["when"] = {};
  if (p.match.tool !== undefined) when.tool = p.match.tool;
  if (p.match.command_matches !== undefined) when.command_matches = p.match.command_matches;
  if (p.match.path_matches !== undefined) when.path_matches = p.match.path_matches;
  if (p.match.url_matches !== undefined) when.url_matches = p.match.url_matches;
  if (p.match.repo_in !== undefined) when.repo_in = p.match.repo_in;
  const reason = decidedBy
    ? `promoted from ${decidedBy} at ${new Date().toISOString()}`
    : `promoted at ${new Date().toISOString()}`;
  return {
    name: p.rule_name,
    when,
    action: "allow",
    reason,
  };
}

const HEADER = `# Auto-generated by Sentinel.
#
# このファイルは PWA で "Allow & promote to rule" を押すたびに追記されます。
# 直接編集も可能ですが、policy.yaml に移したいルールはこちらから手動で移してください。
# daemon は起動時 / promote 時 / SIGHUP 時にこのファイルを再読込します。
`;

/**
 * generated ファイルに 1 件追加する。atomic な write (tmp → rename)。
 * 同名の rule が既にあれば置き換える (重複防止)。
 */
export async function appendGeneratedRule(path: string, rule: PolicyRule): Promise<PolicyRule[]> {
  const existing = await loadGeneratedRules(path);
  const filtered = existing.filter((r) => r.name !== rule.name);
  filtered.push(rule);

  const body = stringifyYaml({ rules: filtered }, { lineWidth: 0 });
  const content = `${HEADER}\n${body}`;
  const tmp = `${path}.${process.pid}.tmp`;
  await writeFile(tmp, content, { mode: 0o600 });
  await rename(tmp, path);
  return filtered;
}
